### ISSUE TITLE
formatCurrency should return 2 digits after the decimal (sometimes truncates to 1 or 0 digits after the decimal point)

### ISSUE THREAD

**Issue by mebaran** [rstudio/DT#100]
formatCurrency should pad 2 digits after the decimal place.  Ideally, I could pass a digits argument to make the number of digits after the decimal configurable.

**Comment by yihui** [comment]
I'm not sure if it "should", but I agree it will be nice for the number of digits to be configurable.

**Comment by The-Dub** [comment]
Related more or less : when you use FormatPercentage, the filter returns the actual values rather than the formated percentage.

Is there a way to change that in the actual version using some JS code, or has it to be done "under the hood" ?

**Comment by yihui** [comment]
Sorry, but I don't think that is straightforward to do even using JavaScript. The filter ranges are written here: https://github.com/rstudio/DT/blob/a0fc3bf7b8e5061f2bc125e27ba1cc759ab41d69/inst/htmlwidgets/datatables.js#L225 The problem is that the column filters are not part of the official DataTables API. They are not related to the column formatters at all. There might be a way to achieve what you want, but I guess the work is not trivial...

**Comment by The-Dub** [comment]
Ok, I'll try to take a look at it, but unfortunately my JS knowledge is very close to the JS knowledge of  a potato... :-]

I showed it to a colleague who knows his stuff, and told me to look into formating the output of the filter (the numbers), so I'll check that.

**Comment by mebaran** [comment]
Just for consideration, what if formatCurrency had an added "pretty" option that would preprocess the input with prettyNum before handing it back to Datatables?  This would let us handle the number formatting with native R facilities.

Reviewing the Datatables documentation, the sorting filter should be able to parse such numbers transparently (particularly if we set the right decimal mark and big mark in the JS call to datatable() as per the documentation: https://datatables.net/reference/option/language.decimal)  Maybe worth investigating?

**Comment by yihui** [comment]
Done. `formatCurrency()` will round numbers to 2 decimal places by default, and it is configurable via the new argument `digits`.

**Comment by mawilliam** [comment]
I am still having this problem and I receive an error saying 'unused arguments' when trying to specify `digits=2`. I just upgraded to R version 3.2.4. Below is an example and you can access the data [here](https://s3.amazonaws.com/pix-media/Data+for+TreefortBnB+Puzzle.csv).
```{r}
data.df = read.csv("Data+for+TreefortBnB+Puzzle.csv",header=T,stringsAsFactors = F)
data.df$City_State <- paste(data.df$City,data.df$State, sep = ", ")
med_city_price <- data.df %>% group_by(City_State) %>%
  summarise(Units = n(), Median..Price=median(X..Price)) %>% 
  top_n(100,Units) %>%
  arrange(desc(Median..Price))
datatable(med_city_price, colnames = c("City, State" = "City_State","Median Price" = "Median..Price")) %>%
  formatCurrency("Median Price")
```
In this case, there are not two decimal places for each Median Price and I am not able to use the `digits=2` argument.

**Comment by yihui** [comment]
@mawilliam Please make sure you are using the development version of DT: https://github.com/rstudio/DT#installation
