### ISSUE TITLE
Column search returns no rows when '&' is in the search term

### ISSUE THREAD

**Issue by dfriend21** [rstudio/DT#1075]
When a column has a value with an ampersand, searching for that value returns no results.

Example:

```r
library(shiny)
library(DT)

ui <- fluidPage(
  DT::dataTableOutput("table")
)

server <- function(session, input, output){
  output$table <- DT::renderDataTable({
    data.frame(a = factor(c("A", "B", "C&", "D")), b = 1:4)
  }, filter = "top")
}

shinyApp(ui, server)
```

<details>
<summary>
Screenshots from the example
</summary>
<br>
The table, pre-filtering:

![image](https://github.com/rstudio/DT/assets/7896671/c1447e3b-cd10-4398-be17-538ccb6645f1)

After searching column 'a' for the value 'C&':

![image](https://github.com/rstudio/DT/assets/7896671/c82197ec-7377-479c-83dc-2795ac8cc583)
</details>

<details>
<summary>
Output of `xfun::session_info('DT')`
</summary>
<br>

```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045), RStudio 2023.6.0.421


Locale:
  LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
  LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

Package version:
  base64enc_0.1.3   bslib_0.5.0       cachem_1.0.8      cli_3.6.1         crosstalk_1.2.0   digest_0.6.33    
  DT_0.28.1         ellipsis_0.3.2    evaluate_0.21     fastmap_1.1.1     fontawesome_0.5.1 fs_1.6.2         
  glue_1.6.2        graphics_4.3.1    grDevices_4.3.1   highr_0.10        htmltools_0.5.5   htmlwidgets_1.6.2
  jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.43        later_1.3.1       lazyeval_0.2.2    lifecycle_1.0.3  
  magrittr_2.0.3    memoise_2.0.1     methods_4.3.1     mime_0.12         promises_1.2.0.1  R6_2.5.1         
  rappdirs_0.3.3    Rcpp_1.0.11       rlang_1.1.1       rmarkdown_2.23    sass_0.4.6        stats_4.3.1      
  stringi_1.7.12    stringr_1.5.0     tinytex_0.45      tools_4.3.1       utils_4.3.1       vctrs_0.6.3      
  xfun_0.39         yaml_2.3.7
```

</details>

<details>
<summary>
Promises
</summary>
<br>

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.org/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

</details>

**Comment by olivier7121** [comment]
I am experiencing exactly the same issue.

Output of `xfun::session_info('DT')`
```
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045), RStudio 2023.6.1.524


Locale: LC_COLLATE=French_France.utf8  LC_CTYPE=French_France.utf8    LC_MONETARY=French_France.utf8 LC_NUMERIC=C                   LC_TIME=French_France.utf8    

time zone: Europe/Berlin
tzcode source: internal

Package version:
  base64enc_0.1.3   bslib_0.5.0       cachem_1.0.8      cli_3.6.1         crosstalk_1.2.0   digest_0.6.33     DT_0.28           ellipsis_0.3.2    evaluate_0.21    
  fastmap_1.1.1     fontawesome_0.5.1 fs_1.6.3          glue_1.6.2        graphics_4.3.1    grDevices_4.3.1   highr_0.10        htmltools_0.5.5   htmlwidgets_1.6.2
  jquerylib_0.1.4   jsonlite_1.8.7    knitr_1.43        later_1.3.1       lazyeval_0.2.2    lifecycle_1.0.3   magrittr_2.0.3    memoise_2.0.1     methods_4.3.1    
  mime_0.12         promises_1.2.0.1  R6_2.5.1          rappdirs_0.3.3    Rcpp_1.0.11       rlang_1.1.1       rmarkdown_2.23    sass_0.4.7        stats_4.3.1      
  stringi_1.7.12    stringr_1.5.0     tinytex_0.45      tools_4.3.1       utils_4.3.1       vctrs_0.6.3       xfun_0.39         yaml_2.3.7```

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by prubin73** [comment]
FYI, I ran into this with an ampersand in a factor. The latest version (0.28.3) fixes it when using the column filter, but if I type an ampersand in the table search box (upper right) it still fails.

**Comment by yihui** [comment]
@prubin73 Thanks so much! I just pushed another fix.

**Comment by prubin73** [comment]
Wow, that was fast! Just confirmed that it works for me. Thanks!

**Comment by NadiaPalma500** [comment]
Hello, I have experienced the same error with column search/filter returns no data when '&' is in search term. This was fixed with updating the DT package to v0.33. 

However, I am having another issue where the action button (x) does not work for entries with '&', so you cannot delete them, they will always stay in the box and data will be filtered. It will delete other options without '&', e.g. "Apples", "Bananas", "Orange City", etc; the action button will always work for those entries and delete them. Was wondering if anyone has encountered this before and if there is a fix? Thanks.

**Comment by prubin73** [comment]
> However, I am having another issue where the action button (x) does not work for entries with '&', so you cannot delete them, they will always stay in the box and data will be filtered. It will delete other options without '&', e.g. "Apples", "Bananas", "Orange City", etc; the action button will always work for those entries and delete them.

I assume this is in reference to a column that is a factor. I am not seeing this with DT 0.33. Factor entries containing ampersands have the little 'x' to dismiss them, just like other factors.

**Comment by olivier7121** [comment]
Hi @NadiaPalma500 
> However, I am having another issue where the action button (x) does not work for entries with '&', so you cannot delete them, they will always stay in the box and data will be filtered. It will delete other options without '&', e.g. "Apples", "Bananas", "Orange City", etc; the action button will always work for those entries and delete them. Was wondering if anyone has encountered this before and if there is a fix? Thanks.

I also have exactly the same issue although the column in question is a factor and I do see the action button (x) to delete the entry - but I cannot delete it. I am using shiny 1.10.0.

I can try to provide a reprex.

[EDIT]: [Link to reprex](https://github.com/The-Strategy-Unit/nhp_inputs_report_app/issues/60#issuecomment-2790998590)
