### ISSUE TITLE
Slider Changes Number of Decimal Places When Clicked On

### ISSUE THREAD

**Issue by vnijs** [rstudio/DT#150]
@DarioS I don't think the issue is with Shiny sliders but in DT so I copied your issue here

From https://github.com/rstudio/shiny/issues/908:
"In @vnijs Shiny application, in the Pivot table tab, click in the text box under Total. Now, click on either of the sliders, without necessarily dragging the slider to a new value. They suddenly change to 2 decimal places and 1 row is removed from the tabular display. It is impossible to ever recover all 5 rows of data unless you press the Refresh button of the internet browser to reset the slider to 3 decimal places and show all 5 rows."

**Comment by vnijs** [comment]
Reproducible example.

```r
## in case you want to create the table
library(radiant)
library(DT)
dat <- pivotr("diamonds", cvars = c("clarity","cut"), normalize = "total")$tab %>% filter(cut != "Total")

## data and table - move slider and return to full range in the Total column. Last row disappears.
#dput(dat)
dat <- structure(list(cut = structure(1:5, .Label = c("Fair", "Good", 
"Very Good", "Premium", "Ideal", "Total"), class = "factor"), 
    I1 = c(0.004, 0.001, 0.002, 0.004, 0.002), SI2 = c(0.009, 
    0.021, 0.044, 0.052, 0.05), SI1 = c(0.01, 0.031, 0.057, 0.065, 
    0.077), VS2 = c(0.005, 0.017, 0.044, 0.062, 0.093), VS1 = c(0.004, 
    0.011, 0.033, 0.04, 0.059), VVS2 = c(0.001, 0.004, 0.028, 
    0.014, 0.048), VVS1 = c(0.001, 0.005, 0.013, 0.013, 0.043
    ), IF = c(0, 0.001, 0.005, 0.006, 0.02), Total = c(0.034, 
    0.092, 0.226, 0.257, 0.392)), class = "data.frame", row.names = c(NA, 
-5L), .Names = c("cut", "I1", "SI2", "SI1", "VS2", "VS1", "VVS2", 
"VVS1", "IF", "Total"))
datatable(dat, filter = list(position = "top", clear = FALSE))
```

**Comment by yihui** [comment]
Should be fixed now. Thanks!

**Comment by vnijs** [comment]
Seems this issue can still pop up. See example below. Note that moving the slider back to the original positions does not show 'All' and you cannot remove the filter input completely.

```r
## if you need to recreate
library(radiant)
library(DT)
dat <- pivotr("diamonds", cvars = "clarity", nvar = "price")$tab %>% filter(clarity != "Total")
dput(dat)

## demo
dat <- structure(list(clarity = structure(1:8, .Label = c("I1", "SI2", 
"SI1", "VS2", "VS1", "VVS2", "VVS1", "IF", "Total"), class = "factor"), 
    price = c(4194.775, 5100.18903591682, 3998.57697642164, 3822.96671709531, 
    3789.18099547511, 3337.82042253521, 2608.45982142857, 2411.69696969697
    )), class = "data.frame", row.names = c(NA, -8L), .Names = c("clarity", 
"price"))

datatable(dat, filter = list(position = "top", clear = FALSE))
```

**Comment by yihui** [comment]
I just committed another fix. Please see if you can still find any cases that can fail the sliders :)

**Comment by vnijs** [comment]
Sorry @yihui. The update doesn't seem to fix the example (demo). As soon as you touch the slider, even without moving it, the number of rows is reduced to 7 (from 8). Also, moving the slider back to the original positions does not show 'All' and you cannot remove the filter input completely.

**Comment by vnijs** [comment]
Just tried again and it does work! Thanks @yihui

**Comment by ReportMort** [comment]
I think the scaling routine is adding decimals places that don't exist in the source data, and then the filter displays all of those digits. In the example below, it shows that, depending on the supplied data, the filters display with more or less digits. It's showing a silder with 3 decimal places when using the first 6 rows, a silder with 4 decimal places when using the last 6 rows and a whole string of decimal places when using the entire dataset, even though the source data has been rounded to 2. Can you reproduce? 

```
library(DT)
x <- structure(list(prices = c(313.29, 39.29, 32.15, 24.71,
                                        91.17, 66.14, 88.4, 81.47, 90.02, 88.28, 40.22, 73.62, 60.45,
                                        79.46, 95.08, 52.74, 22.38, 83.37, 52.1, 69.5, 144.83, 23.67,
                                        169.74, 23.87, 103.99, 60.4, 117.85, 46.6, 105.8, 72.8, 39.29,
                                        33.08, 46.09, 52.78, 23.53, 25.56, 29.13, 38.04, 39.54, 49.98,
                                        39, 54.4, 60.22, 43.39, 63.84, 30.63, 78.67, 36.2, 49.44, 33.42,
                                        43.47, 49.92, 46.32, 64.13, 39.58, 35.62, 40.76, 46.18, 49.06
)), .Names = "prices", class = "data.frame", row.names = c(NA,-59L))
x[,'prices'] <- round(x[,'prices'], 2)
x1 <- head(x)
x2 <- tail(x)
x3 <- x

datatable(x1,
          filter = 'top',
          rownames = FALSE) %>% formatCurrency(1)
datatable(x2,
          filter = 'top',
          rownames = FALSE) %>% formatCurrency(1)
datatable(x3,
          filter = 'top',
          rownames = FALSE) %>% formatCurrency(1)
```

**Comment by yihui** [comment]
@ReportMort Thanks! I was able to reproduce the problem, and I just pushed another fix.

**Comment by vnijs** [comment]
Nice clean results and this fixes the original issue. Excellent! Thanks @yihui

**Comment by ReportMort** [comment]
Thanks @yihui. Great work as always.

**Comment by yihui** [comment]
I'm not 100% sure if I have really fixed the issue. Floating point arithmetic problems are so tricky... Please let me know if you discover new issues. Thanks!
