### ISSUE TITLE
datatable  widget initialization fails in boostrap tabs

### ISSUE THREAD

**Issue by paulanka** [rstudio/DT#204]
Hi,
i'm using DT with rmarkdown to produce tab navigation between tables.
datatables in hidden tabs are never initialized unless the window is resized. 
Though i managed to get it work in a previous version, it doesnt work with the latest developpement release.
In the following example, the second table is not initialized.  

    ---
    output:
      html_document:
        toc: true
        theme: united
    ---
    
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#iris1">Iris 1</a></li>
      <li><a data-toggle="tab" href="#iris2">Iris 2</a></li>
    </ul>
    <div class="tab-content">
    
    # iris 1 {#iris1 .tab-pane .active}
    ```{r}
    require(DT)
    datatable(iris[1:10,])
    ```
    
    # iris 2 {#iris2 .tab-pane}
    
    ```{r}
    datatable(iris[1:10,])
    ```
    </div>

**Comment by yihui** [comment]
I'm not able to reproduce this issue. I think we have fixed this issue long time ago in htmlwidgets and DT. Can you show the output of `library(DT); library(rmarkdown); library(htmlwidgets); devtools::session_info()`?

BTW, with the [latest version of rmarkdown on Github](https://github.com/rstudio/rmarkdown), it becomes very simple to write tabbed sections (http://rmarkdown.rstudio.com/html_document_format.html#tabbed_sections):

    ---
    output:
    html_document:
        toc: true
        theme: united
    ---
    
    # Some tabs  {.tabset}
    
    ## iris 1
    
    ```{r}
    library(DT)
    datatable(iris[1:10,])
    ```
    
    ## iris 2
    
    ```{r}
    datatable(iris[1:10,])
    ```

**Comment by paulanka** [comment]
Hi Yihui,
thank you for your reply.  The .tabset option is a really nice feature.
I think my problem is related to the development version of DT. your example works with DT_0.1, but not with DT_0.1.42. (the second tab is empty)
```{r}
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8       
 [4] LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=C             
 [7] LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] DT_0.1.42       rmarkdown_0.9.5 lattice_0.20-33 reshape2_1.2.2  gWidgets_0.0-54 RMySQL_0.10.4  
[7] DBI_0.3.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1      knitr_1.12.3     magrittr_1.5     devtools_1.10.0  colorspace_1.2-2
 [6] stringr_0.6.2    httr_0.5         plyr_1.8         tools_3.2.3      grid_3.2.3      
[11] git2r_0.13.1     withr_1.0.0      htmltools_0.3    yaml_2.1.13      digest_0.6.4    
[16] htmlwidgets_0.5  RCurl_1.95-4.1   evaluate_0.8     memoise_0.2.1    compiler_3.2.3  
[21] jsonlite_0.9.19 
```

**Comment by yihui** [comment]
Oh you are right. It works for the CRAN version but not the current development version. I'll investigate it. Thanks!

**Comment by yihui** [comment]
I think it has been fixed by @jcheng5 via https://github.com/ramnathv/htmlwidgets/pull/184. Please test the current development version of htmlwidgets: `devtools::install_github('ramnathv/htmlwidgets')`

**Comment by MaximeWack** [comment]
With the latest dev versions of DT, rmarkdown, and htmlwidgets it works now for datatables in bootstrap tabs!
Thanks!

However, datatables in bootstrap collapsible panels are still not initialized when the panels start in the collapsed state:

    ```{r}
    library(DT)
    ```
    
    # {.tabset}
    
    ## Tab 1
    
    ```{r}
    datatable(mtcars)
    ```
    
    ## Tab 2
    
    ### <a href="#mtcars" data-toggle="collapse" class="panel-heading">mt cars</a>{.panel .panel-default}
    #### {.panel-body .collapse #mtcars}
    ```{r}
    datatable(mtcars)
    ```

I need to create them with the .in class, then, if I want them to start closed, add some javascript at the end to "show" each tab and collapse all the panels:

```html
<script>
  window.onload = function() {
    $('.nav-tabs li a').tab("show");
    $('.nav-tabs li:first-child a').tab("show");
    $('.panel-body').collapse();
  };
</script>
```

Maybe collapsible elements don't use the same show/hide mechanism as tabs.

Anyway, it's still much better so thank you again!

**Comment by yihui** [comment]
I think you were correct, and I have sent a fix to htmlwidgets: https://github.com/ramnathv/htmlwidgets/pull/195

**Comment by yihui** [comment]
FYI, the current development version of htmlwidgets should work in this case now:

```r
devtools::install_github('ramnathv/htmlwidgets')
```

**Comment by MaximeWack** [comment]
Works like a charm, awesome!
Thanks!
