### ISSUE TITLE
Factor dropdown filter in DT::datatable in shiny dashboards gets cut off

### ISSUE THREAD

**Issue by ajkl** [rstudio/DT#230]
http://stackoverflow.com/q/35168646/559676

I have a factor column and I add filter with DT, the dropdown get cut-off in shiny dashboard.
Also, if you try to set the filter = 'top' all filters are cut off.
I am using mtcars as an example and I make cyl as a factor. (the numeric slider filter works fine, but the factor filter does not). Here is the code and the screen shot.

Note: The factor dropdown filter works in a regular shiny app. The problem is only with shiny dashboards.

```r
## app.R ##
library(shinydashboard)
library(dplyr)
library(shiny)

mtcars$cyl <- as.factor(mtcars$cyl)

ui <- dashboardPage(
  dashboardHeader(title = "Simple Dashboard"),
  ## Sidebar content
  dashboardSidebar(sidebarMenu(
    menuItem(
      "Dashboard", tabName = "dashboard", icon = icon("dashboard")
    ),
    menuItem("Widgets", tabName = "widgets", icon = icon("th"))
  )),
  ## Body content
  dashboardBody(tabItems(
    # First tab content
    tabItem(tabName = "dashboard",
            fluidRow(
              box(plotOutput("plot1", height = 250)),

              box(
                title = "Controls",
                sliderInput("slider", "Number of observations:", 1, 100, 50)
              )
            )),

    # Second tab content
    tabItem(tabName = "widgets",
            fluidRow(DT::dataTableOutput('items_dt')))
  ))
)

server <- function(input, output) {
  set.seed(122)
  histdata <- rnorm(500)

  output$plot1 <- renderPlot({
    data <- histdata[seq_len(input$slider)]
    hist(data)
  })

  output$items_dt = DT::renderDataTable(
    mtcars,
    filter = 'bottom',
    options = list(scrollX = TRUE)
  )
}

shinyApp(ui, server)
```

![image](https://cloud.githubusercontent.com/assets/4917183/12797160/63987fd8-ca77-11e5-80ab-ccc0c7c9f9b3.png)

![image](https://cloud.githubusercontent.com/assets/4917183/12797168/6e01300a-ca77-11e5-9cfd-fb76485c15d7.png)

filter='top' 
![screen shot 2016-02-03 at 1 27 23 pm](https://cloud.githubusercontent.com/assets/4917183/12797683/ff51934a-ca79-11e5-9c74-534bc2e655d1.png)

**Comment by yihui** [comment]
Thanks for the report! I can reproduce it, but it does not seem to be easy to fix... I'll take a closer look when I have got time.

**Comment by funnng** [comment]
got the same problem with shinydashboard+DT

**Comment by yihui** [comment]
I think I know the cause now. I'll try to fix it as soon as possible.

**Comment by yihui** [comment]
Should be fixed now.

**Comment by cypresswang** [comment]
Hi Yihui
Just wonder what's the version have you fixed? I am using v0.1, which I believe is the latest available on CRAN and the bug is still there. I found the same issue as well when I was not using shiny.
Here is my code:
```
 datatable(mtcars,filter='top',rownames = F,
          extensions = 'FixedColumns',
          options = list(
            searching = F,
            dom = 't',
            scrollX=T,
            fixedColumns = list(leftColumns = 3)))
```
I found if I remove all the extensions and options, the filter will work just fine. 
`datatable(mtcars,filter='top',rownames = F)`

**Comment by TalSa** [comment]
I am also encountering the same problem. The following works well:

       output$db_table <-DT::renderDataTable(db,
       filter="top", options=list(pageLength = 100),  escape = FALSE)

However, when I add to the options' argument list: "scrollX=TRUE, scrollY=350," the dropdown filter in the factor columns gets cut off.

I am using:
DT: 0.1
Shiny: 0.13.0
shinydashboard: 0.5.1.9000
R: 3.2.3

Many thanks,

Tal

**Comment by yihui** [comment]
@cypresswang @TalSa I was talking about the development version on Github here.

**Comment by catelinn** [comment]
Hello I'm using DT:0.2 the dropdown filter works fine for factor column, however, dropdown filter cut off for character and POSIXct columns now.

**Comment by deepPhong** [comment]
Hello, still having the same issue with DT v0.6 and shinydashboard v0.7.1

**Comment by souradippal** [comment]
Helllo, I am still facing the issue, does anyone have any solution, I tried removing scrollY, but still not working....Anyone found a solution?
