### ISSUE TITLE
'Buttons' extension results in many warnings

### ISSUE THREAD

**Issue by cdeterman** [rstudio/DT#251]
I installed the latest master branch (0.1.51) and tried this simple `datatable` call

```r
library(DT)

datatable(
  iris, options = list(
    dom = 'Bfrtip',
    buttons = list('copy', 'print')
  ),
  extensions = c('Buttons')
)
```

But it resulted in many warnings and a improperly rendered table:

>Warning messages:
1: In file.create(to[okay]) :
  cannot create file 'lib/dt-core-1.10.11/js/jquery.dataTables.min.js', reason 'No such file or directory'
2: In file.create(to[okay]) :
  cannot create file 'lib/dt-core-1.10.11/css/jquery.dataTables.min.css', reason 'No such file or directory'
3: In file.create(to[okay]) :
  cannot create file 'lib/dt-core-1.10.11/css/jquery.dataTables.extra.css', reason 'No such file or directory'
4: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/js/dataTables.buttons.min.js', reason 'No such file or directory'
5: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/js/buttons.flash.min.js', reason 'No such file or directory'
6: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/js/buttons.html5.min.js', reason 'No such file or directory'
7: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/js/buttons.colVis.min.js', reason 'No such file or directory'
8: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/js/buttons.print.min.js', reason 'No such file or directory'
9: In file.create(to[okay]) :
  cannot create file 'lib/dt-ext-buttons-1.10.11/css/buttons.dataTables.min.css', reason 'No such file or directory'

**Comment by yihui** [comment]
Thanks! Actually I have fixed it the other day in the htmltools package. It seems your devtools is not the latest version, otherwise it should pick up the correct version of htmltools on Github.

**Comment by cdeterman** [comment]
I'm still receiving the same warnings and improperly rendered table

`sessionInfo()`
```
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.1.51       devtools_1.10.0 ROracle_1.2-2   DBI_0.3.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3     digest_0.6.9    withr_1.0.1     R6_2.1.2        jsonlite_0.9.19 git2r_0.13.1    magrittr_1.5    httr_1.1.0     
 [9] curl_0.9.6      tools_3.2.3     htmlwidgets_0.6 yaml_2.1.13     memoise_1.0.0   htmltools_0.3.5
```

**Comment by yihui** [comment]
I cannot reproduce it on Windows or OS X. Can you print out `htmltools::copyDependencyToDir`? I guess your htmltools installation is still not correct. You may try

```r
install.packages("htmltools", repos = "https://cran.rstudio.com")
```

**Comment by cdeterman** [comment]
Strange, perhaps I needed to formally restart R for this to work as now it installed and the datatable renders correctly.  Thanks for the help.

**Comment by yihui** [comment]
Yes, before you install packages, it is better to restart R. RStudio will ask if you try to install a package that is already loaded in the current R session.
