### ISSUE TITLE
Can DT clear `rows_selected` after table is gone?

### ISSUE THREAD

**Issue by dracodoc** [rstudio/DT#457]
I often use a `DT` table and rely on rows selected in the table to generate some relevant data. 

```r
# dt row selection after table gone
library(shiny)
library(DT)

ui <- fluidPage(fluidRow(actionButton("remove_table", "Remove Table"),
                         DT::dataTableOutput("table")) )
server <- function(input, output){
  value <- reactiveValues()
  value$dt <- cars
  output$table <- DT::renderDataTable({
    value$dt
  })
  observeEvent(input$remove_table, {
    value$dt <- NULL
    print(input$table_rows_selected)
  })
  observeEvent(input$table_rows_selected, {
    print(input$table_rows_selected)
  })
}
shinyApp(ui = ui, server = server)

```

- If you click the `remove` button, the table data become `NULL` and is not displayed.
- However the selected rows data from `input$table_rows_selected` is left with previous values. You can click `remove` button again and again, and saw the values are still printed.

In my app sometimes I need to update some data dynamically, which caused the table data to first become `NULL`, then change to new values. There are some steps of changes because of multiple reactive values updating at the same time. Then the app will have this behavior:

- table is gone, but the rows selected value is still kept, which caused the code in app to apply those row index on a Null data frame and throw errors.
- table data updated, new table was shown, and the rows selected value is updated. The code above updated and get the correct result.
- so there will be a brief moment that `rows_selected` value cause error.

I have been able to work around this by using `freezeReactiveValue` on it. However I think it make sense to clear this value when the table is destroyed.

**Comment by shrektan** [comment]
It seems like DT need to reset `table_rows_selected` (and other related values, if any) to `NULL` after the datatable's source getting changed.

**Comment by yihui** [comment]
Yes, that makes perfect sense. I'll see if this can be done in the next release. Thanks for the suggestion!

**Comment by yihui** [comment]
Should be fixed now. Thanks for the report!

**Comment by johnbde** [comment]
This is still an issue. I am using DT 0.4 version and R3.5. Example in the original post still does not work.
Another example shown below. If you select rows and change drop down. it still shows previously selected rows.
```
library(shiny)
library(shinydashboard)
library(DT)
library(dplyr)

# FETCH DATA
mydata = mtcars
mydata$id = 1:nrow(mydata)

#Dashboard header carrying the title of the dashboard
header <- dashboardHeader(title = "My Dashboard")

######################
# Dashboard Sidebar
######################

sidebar <- dashboardSidebar(
  sidebarMenu(
    menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
    selectInput(
      "hyp",
      "Select:", 
      list(
        'All','drat','wt'
      ) , 
      selected =  "All", selectize = TRUE)
  )
)

# Dashboard Body

frow1 <- fluidRow(
  valueBoxOutput("value1")
)





frow2 <- fluidRow(
  box(DT::dataTableOutput("mytable"), width = 12)
)

# combine the two fluid rows to make the body
body <- dashboardBody(frow1, frow2)

####################
# Dashboard Page
###################
ui <- dashboardPage(title = 'Model', header, sidebar, body, skin='purple')

####################
# SERVER
###################

d = data.frame(stringsAsFactors = F)
server <- function(input, output, session) {
  dd = reactiveValues(select = NULL, select2 = NULL)
  
  # Render Table
  output$mytable = DT::renderDataTable({
    DT::datatable(test(), rownames= FALSE, extensions = c('FixedHeader'),
                  filter = 'top', 
                  selection=list(mode = 'multiple'), 
                  options = list( autoWidth = TRUE,
                                  scrollX = TRUE, 
                                  orderClasses = TRUE,
                                  pageLength = 50, 
                                  fixedHeader = TRUE,
                                  dom = 'Bfrtip'
                  ),escape=F)
  }
  )
  
  
  proxy = DT::dataTableProxy('mytable')
  
  test <- reactive({
    if(input$hyp == 'All') {
      result = mydata
    } else {
      result = mydata %>% dplyr::filter(UQ(as.name(input$hyp)) <= 3)
    }
    return(result)
  })
  
  
  mt = reactiveValues(ndt= NULL)
  dd = reactiveValues(select = NULL)
  fd = reactiveValues(k=data.frame(stringsAsFactors = F))
  
  observe({
    if(!is.null(input$mytable_rows_selected)){
      dd$select =  input$mytable_rows_selected
      mt$ndt = test()[dd$select,]
    }
  })
  
  
  observeEvent(input$hyp, {selectRows(proxy, NULL)})
  
  proxy = DT::dataTableProxy('mytable')
  observe({print(mt$ndt )})
  
  #creating the valueBoxOutput content
  output$value1 <- renderValueBox({
    c_a = sum(mydata[mt$ndt[["id"]],"mpg"], na.rm = T)
    valueBox(
      formatC(c_a, format="d", big.mark=',')
      ,'Total MPG'
      ,icon = icon("th",lib='glyphicon')
      ,color = "purple")

```
