### ISSUE TITLE
DT does not show up in Shiny after last upgrade

### ISSUE THREAD

**Issue by olbran** [rstudio/DT#489]
Hi 
I am developping a Shiny app that requires the DT package. I have noticed that since the last upgrade (0.3) tables cannot be displayed as if they were not created. The js console indicates a 404 error. I guess this is a similar problem as the one described here : https://github.com/rstudio/DT/issues/266

It may be caused by another problem I am far from being able to understand. However, my app is fully running after a downgrade to the 0.2 version. This is an indication of something going wrong after the upgrade.

**Comment by subhashjaini** [comment]
I am having the exact same issue on my app.  I will admit, there is complexity (nested datatable creations) but it worked in .2

**Comment by yihui** [comment]
@subhashjaini Could you send a reproducible example to me? You can replace your actual data with random data. BTW, does the dev version work?

```r
devtools::install_github('rstudio/DT')
```

**Comment by yihui** [comment]
@olbran sent me an example by email. I was able to reproduce the problem with DT 0.3, and the problem was gone after I install the dev version. I think the problem has been fixed in 8d2518435422a30ad0bac17a95373a687b0eb4e2. @subhashjaini Could you verify it with the dev version of DT?

**Comment by subhashjaini** [comment]
It's very hard to reproduce this thing... but I will try the dev version
tomorrow on my app!

Thanks! :D

**Comment by ben519** [comment]
I also experienced this.  Table rendered fine in v0.2. Wouldn't render in v0.3. Works in 0.3.3.  Thanks!

**Comment by yihui** [comment]
@UOTLeop Same question for you: did you try the development version of DT here?

**Comment by UOTLeop** [comment]
ERROR: package or namespace load failed for ‘DT’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘htmlwidgets’ 0.9 is already loaded, but >= 1.0 is required

**Comment by yihui** [comment]
@UOTLeop 
[Is everything up-to-date?](https://yihui.name/en/2017/05/when-in-doubt-upgrade/) e.g. `update.packages(ask = FALSE, checkBuilt = TRUE)`

**Comment by UOTLeop** [comment]
Thanks, everything work fine ;). Appreciate 👍

**Comment by yihui** [comment]
@UOTLeop Excellent! Thanks for the confirmation!

**Comment by subhashjaini** [comment]
the dev version works!

Out of curiosity, what did y'all change?! :)

**Comment by yihui** [comment]
It was fixed via 8d2518435422a30ad0bac17a95373a687b0eb4e2.

The new version of DT is on CRAN now: https://cran.r-project.org/web/packages/DT/ (Windows/macOS binary packages will come in the next couple of days, but you can install from source; see #488).

**Comment by elliefewings** [comment]
Hi, I am still having this issue with the new version of DT (v 0.4). My issue seems to be with the size of my input Rdata file because when I truncated it to make a reproducible short example it actually worked fine... I'm afraid the data is too large to upload here, so I have put it in my repository with the code.

Any tips you can give would be greatly appreciated!

 [(https://github.com/elliefewings/App_example)](url)

**Comment by shrektan** [comment]
@elliefewings It seems to take a lifetime to download your data and your app logic is also far from __minimal__ for me...

- Please paste your `sessionInfo()` and ensure that you've tried the dev version of DT already.
- Please describe what really happens (snapshot would be better)
- I see your app logic and suspect that the data passed to `datatable` may be `NULL`. As you can see from the following example, `NULL` value will lead to a hiding `datatable`.

```r
library(DT)
library(shiny)
ui <- fluidPage(
  actionButton("click", "click"),
  fluidRow(
    DTOutput("tbl")
  )
)  
server <- function(input, output) {
  output$tbl <- renderDT(iris)
  observeEvent(
    input$click,
    output$tbl <- renderDT(NULL)  
  )
}
runApp(mget(c("ui", "server")))
```

**Comment by elliefewings** [comment]
Thanks for replying. As I said, I tried to create a smaller version of the data but couldn't reproduce the error with this. I have shortened the code (at the same link) so hopefully it is slightly closer to 'minimal'. 

The app works as desired when run locally (which leads me to believe the data can't be null) but receives the following error when deployed. Yes I have tried the dev version with no success. 

![image](https://user-images.githubusercontent.com/18575687/37608483-980cd948-2b92-11e8-8087-50c61c3419b4.png)

Session info is below:
`R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Scientific Linux 7.4 (Nitrogen)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.7.4   ggplot2_2.2.1 reshape_0.8.7 DT_0.4        shiny_1.0.5  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     pillar_1.2.1     plyr_1.8.4       bindr_0.1.1      bitops_1.0-6     tools_3.3.3      digest_0.6.15    packrat_0.4.9-1 
 [9] jsonlite_1.5     tibble_1.4.2     gtable_0.2.0     pkgconfig_2.0.1  rlang_0.2.0      crosstalk_1.0.0  yaml_2.1.18      bindrcpp_0.2    
[17] htmlwidgets_1.0  grid_3.3.3       glue_1.2.0       R6_2.2.2         RJSONIO_1.3-0    magrittr_1.5     scales_0.5.0     htmltools_0.3.6 
[25] rsconnect_0.8.8  assertthat_0.2.0 mime_0.5         xtable_1.8-2     colorspace_1.3-2 httpuv_1.3.6.2   RCurl_1.95-4.10  lazyeval_0.2.1  
[33] munsell_0.4.3   `

**Comment by shrektan** [comment]
@elliefewings You mean that it only happens when being deployed to shinyapps.io, right? Then your local machine's info is irrelevant. Since I've never used `shinyapps.io` before, it beyond my knowledge.

Maybe what you can try is to ensure that the `shinyapps.io` uses the latest CRAN version (because I tested it and the CRAN version works, too).

**Comment by elliefewings** [comment]
I was under the impression that when you deploy the app it uploads whatever version of the packages you use locally? Otherwise using different versions of DT as has been done by the people on this page (who seem to come across the same problem) wouldn't fix the problem? 
Although I couldn't find the specific documentation on this.

Thanks for your help.  Can you ask someone who has experience with this to lend a hand?

**Comment by shrektan** [comment]
Sorry I can't. Accessing to _shinyapps.io_ is extremely slow in China so we don't use it. I suggest you read [the official doc](http://docs.rstudio.com/shinyapps.io/). 

According to [shinyapps - applications](http://docs.rstudio.com/shinyapps.io/applications.html):

> shinyapps.io limits the availability of system resources that an instance can consume by its type. The table below outlines the various instance types and how much memory is allowed for each. By default, shinyapps.io deploys all applications on ‘large’ instances, which are allowed to use 1024 MB of memory.

I bet that your app is running on an instance with 1024MB memory which is definitely insufficient because your raw data only occupies 800MB on my Mac and everytime you filter something it gets partially copied. So it needs at least 1.6 GB or more to run.

**Comment by elliefewings** [comment]
Ok well thanks for trying. Perhaps you are right and it is an issue with data size. I might have to try and move it to my own server.

Thanks for your help.
