### ISSUE TITLE
accents not working 

### ISSUE THREAD

**Issue by ignacio82** [rstudio/DT#62]
For example:

    library(rvest)
    library(DT)
    library(dplyr)
    url <- "http://concursos.justucuman.gov.ar/ayudante_judicial_capital_2014/om_final/consulta_ayud_jud_cap_2014_omd.asp"
    merito <- url %>%
      html() %>%
      html_nodes(xpath='//*[@id="box-table-a"]') %>%
      html_table(fill=T)
    merito <- merito[[1]] 
    merito$Acordada <- grepl(pattern = 'Acordada', x = merito$Incorporado)
    merito <- merito  %>% 
      filter(Acordada==F) %>%
      select(3) %>%
      slice(4:7)
    
    datatable(merito, rownames = FALSE)

Instead of rendering MARÍA it renders MARÃA

Is it possible to fix this?

I'm running the latest version of DT on the docker image rocker/hadleyverse:latest

Thanks!

**Comment by yihui** [comment]
My guess is that the problem should be fixed in the latest development version of htmltools (https://github.com/rstudio/htmltools/pull/21):

    devtools::install_github('rstudio/htmltools')

Let me know if it is not. Thanks!

**Comment by ignacio82** [comment]
Upgrading htmltools did not solve the problem. But, adding this line before calling datatable does:

    Encoding(merito$`Apellido y Nombre`) <- "UTF-8"

Thanks!

**Comment by yihui** [comment]
Sounds like you need to specify the encoding in `html()` then.

```r
library(rvest)
library(DT)
library(dplyr)
url <- "http://concursos.justucuman.gov.ar/ayudante_judicial_capital_2014/om_final/consulta_ayud_jud_cap_2014_omd.asp"
merito <- url %>%
  html(encoding = 'UTF-8') %>%
  html_nodes(xpath='//*[@id="box-table-a"]') %>%
  html_table(fill=T)
merito <- merito[[1]] 
merito$Acordada <- grepl(pattern = 'Acordada', x = merito$Incorporado)
merito <- merito  %>% 
  filter(Acordada==F) %>%
  select(3) %>%
  slice(4:7)
```

**Comment by ignacio82** [comment]
That did the trick! Thanks!!
