### ISSUE TITLE
Issue with DT SearchPanes : only first 10 unique values appear in the panes

### ISSUE THREAD

**Issue by JonasMandel** [rstudio/DT#820]
Hi there, 

I am trying to use the new SearchPanes and Buttons features from the DT package for filtering/selecting rows of a (rather large) datatable within a shiny app, along with the Scroller extension but I have problems with the searchpanes: when using both SearchPanes and Scroller only the first 10 unique values appear in the searchpanes.

Minimal example with the dataset gapminder form package gapminder:

```
library(shiny)
library(DT)
library(magrittr)
library(gapminder)

shinyApp(
  ui = fluidPage(
    dataTableOutput('tbl')
  ),

  server = function(input, output) {
    output$tbl = renderDataTable(server=FALSE, {
      datatable(gapminder,
        rownames = FALSE,
        colnames = c("Country", "Continent", "Year",
                     "Life Exp", "Population", "GDP per capita"),
        extensions = c("SearchPanes", "Select", "Buttons", "Scroller"),
        options = list(
          dom = "Brtip",
          buttons = list("searchPanes"),
          language = list(searchPanes = list(collapse = "Filter Rows")),
          scrollY = 500,
          scroller = TRUE,
          columnDefs = list(
            list(searchPanes = list(show = FALSE), targets = c(3:5)),
            list(searchPanes = list(controls = FALSE), targets = 0:2),
            list(className = "dt-center", targets = 0:5)
          )
        ),
        selection="none"
      ) %>% 
      formatRound(4, 1) %>% 
      formatRound(5, 0) %>% 
      formatCurrency(6, digits = 0)
    })
  }
)
```
In the searchpanes of this example app the filtering choices for "Country" only go from "Afghanistan" to "Belgium", while there are much more countries in the dataset:

![screenshot of SearchPanes issue in shiny app](https://user-images.githubusercontent.com/32480212/85269932-df151f00-b478-11ea-86ef-3da7bdfc5ece.PNG)

However if I don't use the Scroller extension, the problem disappears:

```
shinyApp(
  ui = fluidPage(
    dataTableOutput('tbl')
  ),

  server = function(input, output) {
    output$tbl = renderDataTable(server=FALSE, {
      datatable(gapminder,
        rownames = FALSE,
        colnames = c("Country", "Continent", "Year",
                     "Life Exp", "Population", "GDP per capita"),
        extensions = c("SearchPanes", "Select", "Buttons"),
        options = list(
          dom = "Brtip",
          buttons = list("searchPanes"),
          language = list(searchPanes = list(collapse = "Filter Rows")),
          columnDefs = list(
            list(searchPanes = list(show = FALSE), targets = c(3:5)),
            list(searchPanes = list(controls = FALSE), targets = 0:2),
            list(className = "dt-center", targets = 0:5)
          )
        ),
        selection="none"
      ) %>% 
      formatRound(4, 1) %>% 
      formatRound(5, 0) %>% 
      formatCurrency(6, digits = 0)
    })
  }
)
```

![SearchPanes issue disappears when Scroller isn't used](https://user-images.githubusercontent.com/32480212/85270037-079d1900-b479-11ea-9910-e971a8325d55.PNG)

I would really like to use the Scroller extension and the SearchPanes extension together. Is there a solution that I missed for this issue ?

This question was asked on StackOverflow 3 days ago with no answer: https://stackoverflow.com/questions/62466062/problem-with-dt-searchpanes-only-first-10-unique-values-appear-in-the-panes

Jonas

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('DT')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/DT')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by shrektan** [comment]
Yes, I can reproduce this issue. But it looks like Scroller and SearchPanes extension just can't get along with each other. I'm afraid that there's nothing we can help with this...

**Comment by stla** [comment]
See [here](https://datatables.net/forums/discussion/62807/searchpanes-button-filtering-value-only-show-10-from-all-available-values-with-scroller-extension). This will be fixed in the next release of `SearchPanes`. With the current version, a fix consists in setting the option `paging = FALSE` like this:
```
buttons = list(
  list(
    extend = "searchPanes",
    config = list(
      dtOpts = list(
        paging = FALSE
      )
    )
  )
)
```

**Comment by shrektan** [comment]
@stla Thanks for investigating this so this should be fixed when we update the extension source file.

**Comment by pembletonc** [comment]
Hello, I've tried to implement your recommendation above, and followed [this code](http://live.datatables.net/hacugute/1/edit) but still can't get it working. Am I missing something in my layout?

```
output$tbl_main <-  DT::renderDT(server = FALSE, { 
    datatable(df, 
              extensions = c('SearchPanes','Select','Buttons','Scroller'),
              rownames = FALSE,
              selection = "none",
              options = list(dom = 'Blfrtip',
                             autoWidth = TRUE,
                             deferRender = TRUE,
                             scrollY = 400,
                             scroller = TRUE,
                             buttons = list(
                               list(
                                 extend = "searchPanes", 
                                 config = list(
                                   layout = 'columns-2',
                                   dtOpts = list(
                                     dom = "ti",
                                     info = TRUE,
                                     paging = FALSE
                                     )
                                   )
                                 )
                               ),
                             language = list(searchPanes = list(collapse = "Filter Rows")),
                             columnDefs = list(
                               list(searchPanes = list(show = FALSE), targets = 2),
                               list(searchPanes = list(controls = FALSE), targets = 0:1),
                               list(className = "dt-center", targets = 0:1)))
              )
    } )  
}

```

**Comment by shrektan** [comment]
@pembletonc I'm afraid it won't work until the SearchPane extension gets updated. 

I mean, after upgrading the SearchPane's JS source file, the following code will work.

```r
library(shiny)
library(DT)
library(magrittr)
library(gapminder)

shinyApp(
  ui = fluidPage(
    dataTableOutput('tbl')
  ),
  
  server = function(input, output) {
    output$tbl = renderDataTable(server=FALSE, {
      datatable(gapminder,
                rownames = FALSE,
                colnames = c("Country", "Continent", "Year",
                             "Life Exp", "Population", "GDP per capita"),
                extensions = c("SearchPanes", "Select", "Buttons", "Scroller"),
                options = list(
                  dom = "Brtip",
                  buttons = list(
                    list(
                      extend = "searchPanes",
                      config = list(
                        dtOpts = list(
                          paging = FALSE
                        )
                      )
                    )
                  ),
                  language = list(searchPanes = list(collapse = "Filter Rows")),
                  scrollY = 500,
                  scroller = TRUE,
                  columnDefs = list(
                    list(searchPanes = list(show = FALSE), targets = c(3:5)),
                    list(searchPanes = list(controls = FALSE), targets = 0:2),
                    list(className = "dt-center", targets = 0:5)
                  )
                ),
                selection="none"
      ) %>% 
        formatRound(4, 1) %>% 
        formatRound(5, 0) %>% 
        formatCurrency(6, digits = 0)
    })
  }
)
```

<img width="1321" alt="image" src="https://user-images.githubusercontent.com/8368933/90419422-1c98d000-e0e9-11ea-865f-7d29a1d08651.png">
